export const JOBS = [
  {
    id: 1,
    title: 'Software Engineering Intern',
    company: 'Google',
    logo: 'G',
    color: '#1a73e8',
    type: 'Internship',
    mode: 'Remote',
    tags: ['React', 'JavaScript', 'TypeScript'],
    stipend: '$3,500/mo',
    location: 'Remote (US/EU)',
    posted: '2d ago',
    featured: true,
    category: 'Technology',
    desc: 'Work with the Chrome DevTools team to build next-gen developer experiences.',
  },
  {
    id: 2,
    title: 'Data Analyst Intern',
    company: 'Spotify',
    logo: 'S',
    color: '#1DB954',
    type: 'Internship',
    mode: 'Hybrid',
    tags: ['Python', 'SQL', 'Tableau'],
    stipend: '$2,800/mo',
    location: 'Stockholm, Sweden',
    posted: '1d ago',
    featured: false,
    category: 'Data Science',
    desc: 'Analyze user listening patterns and build dashboards for business decisions.',
  },
  {
    id: 3,
    title: 'Product Designer',
    company: 'Stripe',
    logo: 'S',
    color: '#635BFF',
    type: 'Full-time',
    mode: 'On-site',
    tags: ['Figma', 'Design Systems', 'Fresher OK'],
    stipend: '$80k - $120k/yr',
    location: 'San Francisco, CA',
    posted: '3d ago',
    featured: false,
    category: 'Design',
    desc: 'Design seamless payment experiences for millions of merchants worldwide.',
  },
  {
    id: 4,
    title: 'Backend Engineer Intern',
    company: 'Airbnb',
    logo: 'A',
    color: '#FF5A5F',
    type: 'Internship',
    mode: 'Hybrid',
    tags: ['Node.js', 'AWS', 'Microservices'],
    stipend: '$4,000/mo',
    location: 'London, UK',
    posted: '5h ago',
    featured: true,
    category: 'Technology',
    desc: 'Scale backend services handling millions of bookings globally.',
  },
  {
    id: 5,
    title: 'Growth Marketing Intern',
    company: 'Notion',
    logo: 'N',
    color: '#000000',
    type: 'Part-time',
    mode: 'Remote',
    tags: ['SEO', 'Content', 'Analytics'],
    stipend: '$2,000/mo',
    location: 'Remote',
    posted: '5d ago',
    featured: false,
    category: 'Marketing',
    desc: 'Drive organic growth campaigns for the leading workspace platform.',
  },
  {
    id: 6,
    title: 'ML Research Intern',
    company: 'OpenAI',
    logo: 'O',
    color: '#10A37F',
    type: 'Internship',
    mode: 'On-site',
    tags: ['Python', 'PyTorch', 'NLP'],
    stipend: '$6,000/mo',
    location: 'San Francisco, CA',
    posted: '1d ago',
    featured: true,
    category: 'Data Science',
    desc: 'Research and develop state-of-the-art large language models.',
  },
  {
    id: 7,
    title: 'Product Manager Intern',
    company: 'Duolingo',
    logo: 'D',
    color: '#58CC02',
    type: 'Internship',
    mode: 'Hybrid',
    tags: ['Product', 'Agile', 'EdTech'],
    stipend: '$3,200/mo',
    location: 'Pittsburgh, PA',
    posted: '2d ago',
    featured: false,
    category: 'Operations',
    desc: 'Shape learning products used by millions of students worldwide.',
  },
  {
    id: 8,
    title: 'Cloud DevOps Engineer',
    company: 'Microsoft',
    logo: 'M',
    color: '#00A4EF',
    type: 'Full-time',
    mode: 'On-site',
    tags: ['Azure', 'Kubernetes', 'CI/CD', 'Fresher OK'],
    stipend: '$90k - $110k/yr',
    location: 'Seattle, WA',
    posted: 'Just now',
    featured: false,
    category: 'Technology',
    desc: 'Build and maintain enterprise-scale cloud infrastructure for Azure clients.',
  },
];

export const COMPANIES = [
  { id: 1, name: 'Google', logo: 'G', color: '#1a73e8', bg: '#e8f0fe', industry: 'Technology', location: 'Global', openings: 142, size: '150k+', desc: 'Search, Cloud & YouTube. World-class engineering internship programs.' },
  { id: 2, name: 'Spotify', logo: 'S', color: '#1DB954', bg: '#e8fdf2', industry: 'Music Tech', location: 'Stockholm, Global', openings: 45, size: '9k+', desc: 'Audio streaming platform — hiring in tech, product, and design.' },
  { id: 3, name: 'Stripe', logo: 'S', color: '#635BFF', bg: '#efefff', industry: 'FinTech', location: 'San Francisco', openings: 87, size: '7k+', desc: 'Financial infrastructure platform for the internet.' },
  { id: 4, name: 'Airbnb', logo: 'A', color: '#FF5A5F', bg: '#ffeef0', industry: 'Travel-Tech', location: 'Global', openings: 54, size: '6k+', desc: 'Global travel community hiring across engineering and design.' },
  { id: 5, name: 'OpenAI', logo: 'O', color: '#10A37F', bg: '#e8fbf5', industry: 'AI Research', location: 'San Francisco', openings: 32, size: '1k+', desc: 'Creating safe AGI that benefits all of humanity.' },
  { id: 6, name: 'Microsoft', logo: 'M', color: '#00A4EF', bg: '#e5f6fd', industry: 'Technology', location: 'Seattle, Global', openings: 300, size: '200k+', desc: 'Empowering every person and organization to achieve more.' }
];

export const COURSES = [
  { id: 1, title: 'Full Stack Web Development', provider: 'InternsBridge Academy', duration: '8 Weeks', rating: '4.9', price: '$49', img: '💻', badge: 'Placement Guarantee' },
  { id: 2, title: 'Data Science & Machine Learning', provider: 'InternsBridge Academy', duration: '12 Weeks', rating: '4.8', price: '$79', img: '📊', badge: 'Popular' },
  { id: 3, title: 'UI/UX Design Masterclass', provider: 'InternsBridge Academy', duration: '6 Weeks', rating: '4.7', price: '$39', img: '🎨', badge: 'New' },
  { id: 4, title: 'Digital Marketing Bootcamp', provider: 'InternsBridge Academy', duration: '4 Weeks', rating: '4.6', price: '$29', img: '📈', badge: null },
];

export const FILTERS = ['All', 'Internship', 'Full-time', 'Part-time', 'Remote', 'Fresher OK'];
export const CATEGORIES = ['Technology', 'Design', 'Data Science', 'Finance', 'Marketing', 'Operations'];

