export const JOBS = [
  {
    id: 1,
    title: 'Frontend Developer Intern',
    company: 'Google India',
    logo: 'G',
    color: '#1a73e8',
    type: 'Internship',
    mode: 'Remote',
    tags: ['React', 'JavaScript', 'TypeScript'],
    stipend: '₹25,000/mo',
    location: 'Remote',
    posted: '2d ago',
    featured: true,
    category: 'Technology',
    desc: 'Work with the Chrome DevTools team to build next-gen developer experiences.',
  },
  {
    id: 2,
    title: 'Data Analyst Intern',
    company: 'Zomato',
    logo: 'Z',
    color: '#e23744',
    type: 'Internship',
    mode: 'Hybrid',
    tags: ['Python', 'SQL', 'Tableau'],
    stipend: '₹18,000/mo',
    location: 'Delhi NCR',
    posted: '1d ago',
    featured: false,
    category: 'Data Science',
    desc: 'Analyze food delivery patterns and build dashboards for business decisions.',
  },
  {
    id: 3,
    title: 'UI/UX Designer',
    company: 'Razorpay',
    logo: 'R',
    color: '#2EB8E6',
    type: 'Full-time',
    mode: 'On-site',
    tags: ['Figma', 'Design Systems', 'Fresher OK'],
    stipend: '₹6–9 LPA',
    location: 'Bengaluru',
    posted: '3d ago',
    featured: false,
    category: 'Design',
    desc: 'Design seamless payment experiences for 8 million+ merchants across India.',
  },
  {
    id: 4,
    title: 'Backend Engineer Intern',
    company: 'Swiggy',
    logo: 'S',
    color: '#fc8019',
    type: 'Internship',
    mode: 'Hybrid',
    tags: ['Node.js', 'AWS', 'Microservices'],
    stipend: '₹30,000/mo',
    location: 'Bengaluru',
    posted: '5h ago',
    featured: true,
    category: 'Technology',
    desc: 'Scale backend services handling 3 million+ orders per day.',
  },
  {
    id: 5,
    title: 'Growth Marketing Intern',
    company: 'MakeMyTrip',
    logo: 'M',
    color: '#e8434a',
    type: 'Part-time',
    mode: 'Remote',
    tags: ['SEO', 'Content', 'Analytics'],
    stipend: '₹12,000/mo',
    location: 'Remote',
    posted: '5d ago',
    featured: false,
    category: 'Marketing',
    desc: 'Drive organic growth campaigns for India\'s leading travel platform.',
  },
  {
    id: 6,
    title: 'ML Research Intern',
    company: 'Flipkart',
    logo: 'F',
    color: '#2874f0',
    type: 'Internship',
    mode: 'On-site',
    tags: ['Python', 'TensorFlow', 'NLP'],
    stipend: '₹35,000/mo',
    location: 'Bengaluru',
    posted: '1d ago',
    featured: true,
    category: 'Data Science',
    desc: 'Research recommendation algorithms that serve 400 million+ customers.',
  },
  {
    id: 7,
    title: 'Product Manager Intern',
    company: 'BYJU\'S',
    logo: 'B',
    color: '#6c3ce1',
    type: 'Internship',
    mode: 'Hybrid',
    tags: ['Product', 'Agile', 'EdTech'],
    stipend: '₹20,000/mo',
    location: 'Bengaluru',
    posted: '2d ago',
    featured: false,
    category: 'Operations',
    desc: 'Shape learning products used by 150 million students worldwide.',
  },
  {
    id: 8,
    title: 'DevOps Engineer',
    company: 'TCS Digital',
    logo: 'T',
    color: '#0079c0',
    type: 'Full-time',
    mode: 'On-site',
    tags: ['Docker', 'Kubernetes', 'CI/CD', 'Fresher OK'],
    stipend: '₹7–10 LPA',
    location: 'Pan India',
    posted: 'Just now',
    featured: false,
    category: 'Technology',
    desc: 'Build and maintain enterprise-scale cloud infrastructure for global clients.',
  },
];

export const COMPANIES = [
  { id: 1, name: 'Google India', logo: 'G', color: '#1a73e8', bg: '#e8f0fe', industry: 'Technology', location: 'Bengaluru, Hyderabad', openings: 14, size: '150k+', desc: 'Search, Cloud & YouTube. World-class engineering internship programs.' },
  { id: 2, name: 'Flipkart', logo: 'F', color: '#2874f0', bg: '#e3f2fd', industry: 'E-Commerce', location: 'Bengaluru', openings: 9, size: '35k+', desc: 'India\'s leading marketplace — tech, product, and business roles.' },
  { id: 3, name: 'Zomato', logo: 'Z', color: '#e23744', bg: '#fce8ea', industry: 'Food-Tech', location: 'Delhi NCR', openings: 7, size: '5k+', desc: 'Food-tech giant with opportunities in product, data, and growth.' },
  { id: 4, name: 'Razorpay', logo: 'R', color: '#2EB8E6', bg: '#e0f7fa', industry: 'FinTech', location: 'Bengaluru', openings: 5, size: '3k+', desc: 'India\'s top payment gateway — hiring engineers and designers.' },
  { id: 5, name: 'BYJU\'S', logo: 'B', color: '#6c3ce1', bg: '#ede7f6', industry: 'EdTech', location: 'Bengaluru', openings: 11, size: '20k+', desc: 'World\'s most valued EdTech — content, tech & marketing roles.' },
  { id: 6, name: 'MakeMyTrip', logo: 'M', color: '#e8434a', bg: '#fce8ea', industry: 'Travel-Tech', location: 'Gurugram', openings: 4, size: '8k+', desc: 'Leading travel platform hiring across tech and customer experience.' },
  { id: 7, name: 'TCS Digital', logo: 'T', color: '#0079c0', bg: '#e3f2fd', industry: 'IT Services', location: 'Pan India', openings: 22, size: '600k+', desc: 'Structured campus hiring programs with global career pathways.' },
  { id: 8, name: 'Swiggy', logo: 'S', color: '#fc8019', bg: '#fff3e0', industry: 'Food Delivery', location: 'Bengaluru', openings: 6, size: '5k+', desc: 'Hyperlocal delivery platform — engineering and growth roles.' },
  { id: 9, name: 'Infosys BPM', logo: 'I', color: '#007cc2', bg: '#e3f2fd', industry: 'IT / BPO', location: 'Mumbai, Pune', openings: 18, size: '250k+', desc: 'Fresher-focused campus hiring for finance, tech & analytics.' },
];

export const FILTERS = ['All', 'Internship', 'Full-time', 'Part-time', 'Remote', 'Fresher OK'];
export const CATEGORIES = ['Technology', 'Design', 'Data Science', 'Finance', 'Marketing', 'Operations'];
